import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type RouteContext = {
  params: Promise<{
    path: string[];
  }>;
};

function getBackendApiBaseUrl(): string {
  const configured =
    process.env.BACKEND_API_URL ||
    process.env.NEXT_PUBLIC_API_BASE_URL ||
    "http://localhost:7070/api/v1";

  const clean = configured.trim().replace(/\/+$/, "");

  if (clean.endsWith("/api/v1")) {
    return clean;
  }

  return `${clean}/api/v1`;
}

function buildTarget(
  request: NextRequest,
  path: string[],
): URL {
  const safePath = path
    .map((segment) =>
      encodeURIComponent(decodeURIComponent(segment)),
    )
    .join("/");

  const target = new URL(
    `${getBackendApiBaseUrl()}/catalog/${safePath}`,
  );

  request.nextUrl.searchParams.forEach((value, key) => {
    target.searchParams.append(key, value);
  });

  return target;
}

async function readBody(
  request: NextRequest,
): Promise<ArrayBuffer | undefined> {
  if (
    request.method === "GET" ||
    request.method === "HEAD"
  ) {
    return undefined;
  }

  const buffer = await request.arrayBuffer();

  return buffer.byteLength ? buffer : undefined;
}

function createBackendHeaders(
  request: NextRequest,
  accessToken?: string,
): Headers {
  const headers = new Headers();

  headers.set(
    "Accept",
    request.headers.get("accept") || "application/json",
  );

  const contentType = request.headers.get("content-type");

  if (contentType) {
    // Preserve multipart boundary generated by the browser.
    headers.set("Content-Type", contentType);
  }

  if (accessToken) {
    headers.set(
      "Authorization",
      `Bearer ${accessToken}`,
    );
  }

  return headers;
}

async function proxyCatalogRequest(
  request: NextRequest,
  context: RouteContext,
) {
  const { path } = await context.params;
  const target = buildTarget(request, path);

  const accessToken =
    request.cookies.get("foodhub_access_token")?.value;

  const body = await readBody(request);

  console.log("[CATALOG PROXY REQUEST]", {
    method: request.method,
    backendUrl: target.toString(),
    authenticated: Boolean(accessToken),
  });

  try {
    const backendResponse = await fetch(target, {
      method: request.method,
      headers: createBackendHeaders(
        request,
        accessToken,
      ),
      body,
      cache: "no-store",
      redirect: "manual",
    });

    const responseBody =
      await backendResponse.arrayBuffer();

    const responseHeaders = new Headers();

    const contentType =
      backendResponse.headers.get("content-type");

    if (contentType) {
      responseHeaders.set("Content-Type", contentType);
    }

    responseHeaders.set("Cache-Control", "no-store");

    if (!backendResponse.ok) {
      console.error("[CATALOG PROXY BACKEND ERROR]", {
        method: request.method,
        backendUrl: target.toString(),
        status: backendResponse.status,
        response: new TextDecoder().decode(responseBody),
      });
    }

    return new NextResponse(
      responseBody.byteLength ? responseBody : null,
      {
        status: backendResponse.status,
        headers: responseHeaders,
      },
    );
  } catch (error) {
    console.error(
      "[CATALOG PROXY CONNECTION ERROR]",
      {
        backendUrl: target.toString(),
        error,
      },
    );

    return NextResponse.json(
      {
        status: 502,
        message:
          "Could not connect to the FoodHub catalog backend.",
      },
      {
        status: 502,
      },
    );
  }
}

export function GET(
  request: NextRequest,
  context: RouteContext,
) {
  return proxyCatalogRequest(request, context);
}

export function POST(
  request: NextRequest,
  context: RouteContext,
) {
  return proxyCatalogRequest(request, context);
}

export function PUT(
  request: NextRequest,
  context: RouteContext,
) {
  return proxyCatalogRequest(request, context);
}

export function PATCH(
  request: NextRequest,
  context: RouteContext,
) {
  return proxyCatalogRequest(request, context);
}

export function DELETE(
  request: NextRequest,
  context: RouteContext,
) {
  return proxyCatalogRequest(request, context);
}
